#pragma once

#include <iostream>
#include <vector>
#include <imgui.h>
#include <imgui-SFML.h>
#include "Core/RenderWindow.h"
#include "Core/Mouse.h"
#include "Core/Keyboard.h"
#include "Core/SoundBuffer.h"
#include "Core/Font.h"
#include "Core/Texture.h"
#include "Core/Sound.h"
#include "Core/Music.h"
#include "Core/Text.h"
#include "Core/CircleShape.h"
#include "Core/RectangleShape.h"
#include "Core/Sprite.h"
#include "Core/AspectRatioCalculator.h"
#include "Core/ScaleCalculator.h"
#include "Core/RandomNumberGenerator.h"